my_app/my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('prof_beton.urls')),
    path('', include('user.urls'))
]

my_app/prof_beton/urls.py
from django.urls import path
from . import views

app_name = 'prof_beton'

urlpatterns = [
    path('', views.home, name='home'),
    path('beton/', views.beton, name='beton'),
]

my_app/user/urls.py
from django.urls import path, include

from . import views

app_name = 'user'
urlpatterns = [
    path('', views.home, name='home'),
    path('register_view/', views.register_view, name='register_view'),
    path('login_view/', views.login_view, name='login_view'),
    path('logout_view/', views.logout_view, name='logout_view')
]

my_app/prof_beton/models.py
from django.db import models

# Create your models here.
'''
Поля Бетона: марка-строка, морозостойкость-строка, водонепроницаемость-строка,
подвижность-строка, цена-десимал
 
'''

class Beton(models.Model):
    name = models.CharField(max_length=100)
    frost_resistance = models.CharField(max_length=10)
    water_resistance = models.CharField(max_length=10)
    mobility = models.CharField(max_length=10)
    price = models.FloatField()


    def __str__(self):
        return self.name

my_app/user/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager


class UserManager(BaseUserManager):

    def create_user(self, phone_number, password=None, **extra_fields):
        if not phone_number:
            raise ValueError('Укажите номер телефона')
        user = self.model(phone_number=phone_number, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, phon_number, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('username', 'admin')
        return self.create_user(phon_number, password, **extra_fields)


class User(AbstractUser):
    phone_number = models.CharField(max_length=15, unique=True)
    is_moderator = models.BooleanField(default=False)

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['email', 'username']

    objects = UserManager()

# Create your models here.

my_app/prof_beton/forms.py
from django import forms
from .models import Beton

class BetonForm(forms.ModelForm):
    class Meta:
        model = Beton
        fields = ['name', 'frost_resistance', 'water_resistance', 'mobility', 'price']
        labels = {'name': 'Марка', 'frost_resistance': 'Морозостойкость',
                  'water_resistance': 'Влагозащита', 'mobility': 'Подвижность', 'price': 'Цена'}

my_app/user/forms.py
from django import forms
from django.core.validators import RegexValidator

from .models import User

class UserRegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'phone_number', 'password']
        labels = {'username': 'Имя пользователя', 'email': 'Эл.почта',
                  'phone_number': 'Номер телефона', 'password': 'Пароль'}

class UserLoginForm(forms.Form):
    phone_number = forms.CharField(label='Номер телефона', max_length=15) #r"^+?1?\d{8,15}$"
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)

my_app/prof_beton/views.py
from django.shortcuts import render
from .models import Beton


# Create your views here.

# Create your views here.

def home(request):
    return render(request, 'prof_beton/home.html')

def beton(request):
    beton = Beton.objects.all()
    return render(request, 'prof_beton/beton.html', context={'beton':beton})

my_app/user/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect

from .forms import UserRegisterForm, UserLoginForm


# Create your views here.

def home(request):
    return render(request, 'user/home.html')

def register_view(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('user:login_view')
    else:
        form = UserRegisterForm()
    return render(request, 'user/register_view.html', context={'form': form})

def login_view(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            phone_number = form.cleaned_data['phone_number']
            password = form.cleaned_data['password']
            user = authenticate(phone_number=phone_number, password=password)
            if user is not None:
                login(request, user)
            return redirect('user:home')
    else:
        form = UserLoginForm()
    return render(request, 'user/login_view.html', context={'form': form})

def profile(request, user_id):
    if request.method == 'POST':
        form = register_view(request.POST)
        if form.is_valid():
            form.save()
            return redirect('goni_bablo:home')
    else:
        user = User.objects.get(id=user_id)
        return render(request, 'registration/profile.html', context={'user':user})

def logout_view(request):
    logout(request)
    return redirect('user:login_view')

my_app/prof_beton/templates/prof_beton/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        header {
            background-color: #333;
            color: #fff;
            padding: 10px 0;
            text-align: center;
        }
        nav {
            background-color: #444;
            text-align: center;
            padding: 10px 0;
        }
        nav a {
            color: #fff;
            text-decoration: none;
            margin: 0 10px;
        }
        nav a:hover {
            color: #ffcc00;
        }
        .content {
            padding: 20px;
        }
    </style>
</head>
<body>
<header>
    <h1><a href="{% url 'prof_beton:home' %}" style="text-decoration: none;color:white"
           >ПРОФБЕТОН</a></h1>
</header>
<nav>
    <a href="{% url 'prof_beton:home' %}">Главная страница</a>
    <a href="{% url 'prof_beton:beton' %}">Бетон</a>
    {% if user.is_authenticated %}
    <a href="{% url 'user:profile' user.id %}"> Привет {{ user.username }}!</a>
    <a href="{% url 'user:logout_view' %}">Пока</a>

    {% else %}
    <a href="{% url 'user:login_view' %}">Вход</a>
    <a href="{% url 'user:register_view' %}">Регистрация</a>
    {% endif %}


</nav>
<div class="content">
    {% block content %}{% endblock %}
</div>
</body>
</html>

my_app/prof_beton/templates/prof_beton/beton.html
{% extends 'prof_beton/base.html' %}
{% block title %} Бетон {% endblock %}

{% block content %}<h1>БЕТОН</h1>

<table>
  <tr>
    <th> Марка </th>
    <th> Морозостойкость </th>
    <th> Водонепроницаемость </th>
    <th> Подвижность </th>
    <th> Цена за м3 </th>
  </tr>
  {% for i in beton %}
  <tr>
    <td>{{ i.name }}</td>
    <td>{{ i.frost_resistance }}</td>
    <td>{{ i.water_resistance }}</td>
    <td>{{ i.mobility }}</td>
    <td>{{ i.price }}</td>
  </tr>
  {% endfor %}
</table>
</body>
</html>

{% endblock %}

my_app/prof_beton/templates/prof_beton/home.html
{% extends 'prof_beton/base.html' %}

{% block title %} Главная страница {% endblock %}

{% block content %}

<h1>Добро пожаловать и передавай за проезд! </h1>

{% endblock %}

my_app/user/templates/user/home.html
{% extends 'prof_beton/base.html' %}

{% block title %} Вход {% endblock %}
<body>
Добро пожаловать!
<br><br><br>
<a href="{% url 'user:login_view'%}">Логин</a>
<a href="{% url 'user:register_view'%}">Регистрация</a>
</body>
</html>

my_app/user/templates/user/login.html
{% extends 'prof_beton/base.html' %}

{% block title %} Вход {% endblock %}

{% block content %}
<h1>Авторизация</h1>
<form action="{% url 'user:login' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Вход!</button>
</form>

my_app/user/templates/user/login_view.html
{% extends 'prof_beton/base.html' %}

{% block title %} Вход {% endblock %}

{% block content %}
<h1>Авторизация</h1>
<form action="{% url 'user:login_view' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Вход!</button>
</form>
{% endblock %}

my_app/user/templates/user/profile.html
{% extends 'prof_beton/base.html' %}

{% block title %}  Профиль {% endblock %}

{% block content %}
<h1>Профиль {{ user.username }}</h1>
<p>Последний вход был совершен: {{ user.last_login }}</p>
{% if user.email %}
<p>Почта: {{user.email }}</p>
{% endif %}


<form action="{% url 'user:'profile" method="post">
    <p>Фамилия {{user.last_name }}</p>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Изменить</button>
</form>
{% endblock %}

my_app/user/templates/user/register_view.html
{% extends 'prof_beton/base.html' %}


<body>
{% block content %}
<h1>Регистрация</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зарегистрироваться</button>
</form>
{% endblock %}
</form>
</body>
</html>